development: 
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: om
  suffix: dev
  username:
  password:

test:
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: om
  suffix: test
  username:
  password:

# production:
#   protocol: 'https'
#   host: localhost
#   port: 5984
#   prefix: om
#   suffix: production
#   username: root
#   password: 123
